<a href="https://colab.research.google.com/github/maacunap76/Especiaizacion_ML_Deep_DMC/blob/main/Deep_learning_program/Modulo_II/Lab_InceptionV3_Model_convolucionales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<h1 align="center"><font size="5">INCEPTION-V3</font></h1>

<h2>Introducción</h2>

En este laboratorio utilizaremos el famoso modelo [Inception-V3](https://keras.io/api/applications/inceptionv3/), un modelo desarrollado por google y brindado a la comunidad cientifica para servir de base de aprendisaje y desarrollo de nuevas herramientas. Nosotros utilizaremos este potente modelo para realizar predicciones sobre imagenes basados en modelos de inteligencia artificial.

<h2>Objetivo</h2>

En este laboratorio, aprenderemos más sobre las aplicaciones de las CNN (Redes neuronales convolucionales).
Esta lección no pretende ser una referencia para<b> aprendizaje automático, aprendizaje profundo, convoluciones</b> o <b>TensorFlow</b>. La intención es dar nociones al usuario sobre estos campos.

<h3> Requisitos previos: </h3>

Conocimientos básicos de Python, Neural Networks, Keras y TensorFlow.

<a id="ref1"></a>
<h2>¿Qué es Inception-V3?</h2>

<b>Inception v3</b>  Es un modelo de reconocimiento de imágenes muy utilizado, el cual se demostró que alcanza una exactitud superior al 78.1% en el conjunto de datos de [ImageNet](http://www.image-net.org/). El modelo representa la culminación de muchas ideas que desarrollaron varios investigadores durante años. Se basa en el documento original: [Reformulación de la arquitectura de Inception para la visión artificial](https://arxiv.org/abs/1512.00567) de Szegedy y otros.

El modelo está formado por bloques de construcción simétricos y asimétricos que incluyen convoluciones, reducción promedio, reducción máxima, concatenaciones, retirados y capas completamente conectadas. La normalización por lotes se usa con frecuencia en todo el modelo y se aplica a las entradas de activación. Las pérdidas se calculan a través de Softmax.

A continuación, se muestra un diagrama de alto nivel del modelo:

<img src="https://cloud.google.com/tpu/docs/images/inceptionv3onc--oview.png" alt="HTML5 Icon" style="width: 600px; height: 800px;">
<div style="text-align: center">Representación gráfica de la arquitectura de InceptionV3 </div>

<h2>Codificando con Tensorflow</h2>

In [1]:
# Importamos las librerias básicas
import tensorflow as tf
from tensorflow import keras

import matplotlib.pyplot as plt
import numpy as np

El modelo Inception-v3 puede importarse directamente desde la librería de keras usando estos simples pasos:

In [2]:
from keras.applications.inception_v3 import InceptionV3, decode_predictions
from keras import backend as K

In [3]:
iv3 = InceptionV3()

96112376/96112376 [==============================] - 1s 0us/step


Listo!, ya tenemos nuestro modelo levantado, ahora veremos un resumen de los componentes del modelo

In [4]:
print(iv3.summary())

Model: "inception_v3"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 299, 299, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv2d (Conv2D)                (None, 149, 149, 32  864         ['input_1[0][0]']                
                                )                                                                 
                                                                                                  
 batch_normalization (BatchNorm  (None, 149, 149, 32  96         ['conv2d[0][0]']                 
 alization)                     )                                                      

Ahora como siguiente paso necesitamos aplicar nuestro modelo sobre alguna imagen a predecir, para esto cargaremos manualmente la imagen de nuestra preferencia:



In [6]:
import keras.utils as image
x = image.img_to_array(image.load_img("/Foto_Alba y Marco.jpg", target_size=(299, 299)))
x.shape


(299, 299, 3)

como se observa, la imagen que cargamos se representa por un tensor de tres dimensiones <b>(pixeles alto , pixeles ancho, 3)</b>

In [7]:
print(x)

[[[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 ...

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]

 [[255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]
  ...
  [255. 255. 255.]
  [255. 255. 255.]
  [255. 255. 255.]]]


Será importantísimo realizar la <b>nomalización</b> de nuestra imagen para poder aplicar el modelo sobre esta

In [8]:
# cambio de rango de 0-255 a -1 a 1
x /= 255
x -= 0.5
x *= 2

In [9]:
print(x)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 ...

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [10]:
x = x.reshape([1, x.shape[0], x.shape[1], x.shape[2]])#se pone 1 pq es una sola imagen

Finalmente aplicaremos el modelo sobre nuestra imagen tratada

In [11]:
y = iv3.predict(x)

1/1 [==============================] - 2s 2s/step


In [12]:
y.shape

(1, 1000)

In [13]:
y

array([[8.00373455e-05, 6.73609029e-05, 3.40258179e-04, 5.45038783e-05,
        1.41764292e-04, 2.51503312e-04, 9.99992335e-05, 3.14087112e-04,
        1.57789153e-04, 7.01798854e-05, 1.80704752e-04, 3.57153156e-04,
        7.82789357e-05, 2.82031862e-04, 1.63286619e-04, 8.94117547e-05,
        2.89014279e-04, 5.48639218e-04, 1.91920815e-04, 3.01484106e-04,
        8.76923295e-05, 6.62655220e-04, 9.14201664e-05, 1.23349688e-04,
        1.19386328e-04, 4.86684090e-04, 1.93677275e-04, 1.29918029e-04,
        5.44777140e-04, 3.60582562e-05, 2.52496451e-04, 2.06164463e-04,
        2.04830154e-04, 2.45302886e-04, 3.19693412e-04, 1.99364236e-04,
        1.87425612e-04, 3.07420647e-04, 5.29859499e-05, 1.79779963e-04,
        6.05387868e-05, 1.50045351e-04, 5.12999715e-04, 1.19426761e-04,
        1.24788581e-04, 1.78542599e-04, 2.01289862e-04, 9.29352173e-05,
        1.30549335e-04, 1.20324752e-04, 5.24115130e-05, 1.17459276e-04,
        9.72425041e-05, 6.15820391e-05, 9.81140402e-05, 1.301328

In [14]:
decode_predictions(y)

35363/35363 [==============================] - 0s 0us/step


[[('n02730930', 'apron', 0.15376422),
  ('n03584829', 'iron', 0.09660537),
  ('n04136333', 'sarong', 0.02103106),
  ('n02666196', 'abacus', 0.020767812),
  ('n02910353', 'buckle', 0.020003147)]]

<a id="ref5"> </a>
<h2> Conclusión </h2>

La aplicación de modelos pre-entrenados es directa y sencilla y nos podrá ayudar en algunos casos, sin embargo si deseamos solucionar un problema específico con Deep Learning deberemos contruir un modelo con nuestra propia data o alguna que nos apoye con el fin.

Como podemos ver, la predicción del modelo es bastante acertada sobre imágenes relativamente sencillas

### Gracias por completar este laboratorio!

# Referencias

https://cloud.google.com/tpu/docs/inception-v3-advanced?hl=es